"""Update users for multi-persona

Revision ID: 3ad216429bd5
Revises: 60a366a0cd86
Create Date: 2026-03-30 18:48:21.364365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ad216429bd5'
down_revision: Union[str, Sequence[str], None] = '60a366a0cd86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('roles', sa.String(), nullable=True))
    op.add_column('users', sa.Column('active_persona', sa.String(), nullable=True))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'active_persona')
    op.drop_column('users', 'roles')
    # ### end Alembic commands ###
